### PR TITLE
Token sharing warning message

### PR DESCRIPTION
**Pull request by Hri7566**
This will add a red-colored 18px log message that informs users not to share their token with a size.

i am aware that the commit log is messy

### CODE REVIEW

**Comment by LapisHusky** [comment]
what's all the ebsprite stuff?

**Comment by Hri7566** [comment]
ebsprite is a script that puts copyrighted earthbound sprites on an mpp web client, the fishing bot sends a server message so it's enabled in whatever room it's in

**Comment by Hri7566** [comment]
in this commit, I have no clue, it was a while ago

**Comment by Hri7566** [comment]
you can request changes or whatever so it's marked as my fault

**Pull request closed without merging**
