### PR TITLE
Disable drum tracks

### PR DESCRIPTION
**Pull request by Hri7566**
Previously, I was told that drum tracks should be enabled anyway because of people who make "strange" standard MIDI format files and utilize drum tracks for audio. This is not our problem to worry about and the official MIDI documentation states that channel 10 is specifically for percussion instruments only.

> MIDI Channels Supported:
• All 16 MIDI channels.
• Each channel can play a variable number of voices (polyphony).
• Each channel can play a different instrument (timbre).
• Key-based Percussion is always on channel 10. 

In the browser, channel 10 is represented as the number value 9, as channel 1 is represented as the number value 0.

### CODE REVIEW

**Comment by LapisHusky** [comment]
There are people who do not want percussion instruments to be played on the piano, which I assume is why you're making this pull request. There are probably also people who do want percussion instruments to be played on the piano, perhaps the midi they're playing only has percussion. There are also midis which do not follow the standard. I'd rather have the channel play by default than not play, that way people can enable and disable it with external software, and avoid confusion about why some midis don't play. I won't accept this pull request in its current state for that reason, but if you implement a setting under MIDI I will accept it.

**Comment by Hri7566** [comment]
There is no need to play percussive tracks because nobody has made any percussive soundpacks.

**Comment by LapisHusky** [comment]
Some people may want to listen to percussive tracks on the piano. Some midis are also improperly made and don't follow the standard, and have notes on channel 10 that aren't meant to be. The latter is not our problem as you stated, but that doesn't mean we can't find a solution on our end. I foresee complaints from people about a blanket block of channel 10, which is why I'd rather have this be an option.

**Comment by Hri7566** [comment]
> Some midis are also improperly made and don't follow the standard, and have notes on channel 10 that aren't meant to be.

As I originally stated, this is not our problem. The official General MIDI Specifications designed channel 10 for percussive instruments, and we should treat it that way. As for listening to percussive tracks on the piano, the supported way to do this should be to edit the standard file's instruments. I never disagreed with the option though, and the toggle shall henceforth decide MIDI channel 10 to be disabled by default, as that is the official documentation.

The MIDI Association declares channel 10 is only to be used for percussion, which is stated under the section "General MIDI Sound Generator Requirements". As Multiplayer Piano's sound generator is largely based on MIDI input, this should be an obligation. The potential requirements listed in the same document may uncover a slew of changes to be made to our beloved client repository.

As for the checkbox, this may be added at a later date.

**Comment by LapisHusky** [comment]
Ok, I understand, and right now I'm fine with having channel 10 disabled by default, but I don't want to disable it until it's easy to re-enable it with a checkbox.

**Pull request closed without merging**
